package com.banana.model;
// Generated Nov 22, 2017 12:40:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyect generated by hbm2java
 */
public class Proyect  implements java.io.Serializable {


     private Integer idProyect;
     private String name;
     private String description;
     private Date dueDate;
     private Date dueTime;
     private Integer progress;
     private Byte active;
     private Set userHasRoles = new HashSet(0);

    public Proyect() {
    }

    public Proyect(String name, String description, Date dueDate, Date dueTime, Integer progress, Byte active, Set userHasRoles) {
       this.name = name;
       this.description = description;
       this.dueDate = dueDate;
       this.dueTime = dueTime;
       this.progress = progress;
       this.active = active;
       this.userHasRoles = userHasRoles;
    }
   
    public Integer getIdProyect() {
        return this.idProyect;
    }
    
    public void setIdProyect(Integer idProyect) {
        this.idProyect = idProyect;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
    public Date getDueTime() {
        return this.dueTime;
    }
    
    public void setDueTime(Date dueTime) {
        this.dueTime = dueTime;
    }
    public Integer getProgress() {
        return this.progress;
    }
    
    public void setProgress(Integer progress) {
        this.progress = progress;
    }
    public Byte getActive() {
        return this.active;
    }
    
    public void setActive(Byte active) {
        this.active = active;
    }
    public Set getUserHasRoles() {
        return this.userHasRoles;
    }
    
    public void setUserHasRoles(Set userHasRoles) {
        this.userHasRoles = userHasRoles;
    }




}


