package com.banana.model;
// Generated Nov 22, 2017 12:40:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private Integer idRole;
     private String name;
     private String description;
     private String privileges;
     private Byte active;
     private Set userHasRoles = new HashSet(0);

    public Role() {
    }

    public Role(String name, String description, String privileges, Byte active, Set userHasRoles) {
       this.name = name;
       this.description = description;
       this.privileges = privileges;
       this.active = active;
       this.userHasRoles = userHasRoles;
    }
   
    public Integer getIdRole() {
        return this.idRole;
    }
    
    public void setIdRole(Integer idRole) {
        this.idRole = idRole;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getPrivileges() {
        return this.privileges;
    }
    
    public void setPrivileges(String privileges) {
        this.privileges = privileges;
    }
    public Byte getActive() {
        return this.active;
    }
    
    public void setActive(Byte active) {
        this.active = active;
    }
    public Set getUserHasRoles() {
        return this.userHasRoles;
    }
    
    public void setUserHasRoles(Set userHasRoles) {
        this.userHasRoles = userHasRoles;
    }




}


