package com.banana.model;
// Generated Nov 22, 2017 12:40:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Task generated by hbm2java
 */
public class Task  implements java.io.Serializable {


     private Integer idTask;
     private String name;
     private String description;
     private Date dueDate;
     private Date dueTime;
     private Byte done;
     private Byte active;
     private Set userHasRoles = new HashSet(0);

    public Task() {
    }

    public Task(String name, String description, Date dueDate, Date dueTime, Byte done, Byte active, Set userHasRoles) {
       this.name = name;
       this.description = description;
       this.dueDate = dueDate;
       this.dueTime = dueTime;
       this.done = done;
       this.active = active;
       this.userHasRoles = userHasRoles;
    }
   
    public Integer getIdTask() {
        return this.idTask;
    }
    
    public void setIdTask(Integer idTask) {
        this.idTask = idTask;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
    public Date getDueTime() {
        return this.dueTime;
    }
    
    public void setDueTime(Date dueTime) {
        this.dueTime = dueTime;
    }
    public Byte getDone() {
        return this.done;
    }
    
    public void setDone(Byte done) {
        this.done = done;
    }
    public Byte getActive() {
        return this.active;
    }
    
    public void setActive(Byte active) {
        this.active = active;
    }
    public Set getUserHasRoles() {
        return this.userHasRoles;
    }
    
    public void setUserHasRoles(Set userHasRoles) {
        this.userHasRoles = userHasRoles;
    }




}


