package com.banana.model;
// Generated Nov 22, 2017 12:40:03 PM by Hibernate Tools 4.3.1



/**
 * UserHasRoleId generated by hbm2java
 */
public class UserHasRoleId  implements java.io.Serializable {


     private int userIdUser;
     private int roleIdRole;
     private int proyectIdProyect;
     private int taskIdTask;

    public UserHasRoleId() {
    }

    public UserHasRoleId(int userIdUser, int roleIdRole, int proyectIdProyect, int taskIdTask) {
       this.userIdUser = userIdUser;
       this.roleIdRole = roleIdRole;
       this.proyectIdProyect = proyectIdProyect;
       this.taskIdTask = taskIdTask;
    }
   
    public int getUserIdUser() {
        return this.userIdUser;
    }
    
    public void setUserIdUser(int userIdUser) {
        this.userIdUser = userIdUser;
    }
    public int getRoleIdRole() {
        return this.roleIdRole;
    }
    
    public void setRoleIdRole(int roleIdRole) {
        this.roleIdRole = roleIdRole;
    }
    public int getProyectIdProyect() {
        return this.proyectIdProyect;
    }
    
    public void setProyectIdProyect(int proyectIdProyect) {
        this.proyectIdProyect = proyectIdProyect;
    }
    public int getTaskIdTask() {
        return this.taskIdTask;
    }
    
    public void setTaskIdTask(int taskIdTask) {
        this.taskIdTask = taskIdTask;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserHasRoleId) ) return false;
		 UserHasRoleId castOther = ( UserHasRoleId ) other; 
         
		 return (this.getUserIdUser()==castOther.getUserIdUser())
 && (this.getRoleIdRole()==castOther.getRoleIdRole())
 && (this.getProyectIdProyect()==castOther.getProyectIdProyect())
 && (this.getTaskIdTask()==castOther.getTaskIdTask());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserIdUser();
         result = 37 * result + this.getRoleIdRole();
         result = 37 * result + this.getProyectIdProyect();
         result = 37 * result + this.getTaskIdTask();
         return result;
   }   


}


